# Generated by Django 4.2.7 on 2026-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('traffic_level', models.CharField(choices=[('free', 'Free Flow'), ('light', 'Light Traffic'), ('moderate', 'Moderate'), ('heavy', 'Heavy Traffic'), ('jam', 'Traffic Jam')], default='free', max_length=20)),
                ('congestion_percentage', models.IntegerField(default=0, help_text='0-100%')),
                ('average_speed', models.FloatField(default=50.0, help_text='km/h')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Traffic Data',
                'verbose_name_plural': 'Traffic Data',
                'ordering': ['street_name'],
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='ambulance_count',
            field=models.IntegerField(default=5, help_text='Number of available ambulances'),
        ),
    ]
